const frames=[['墨・茶','俐落方框 / 茶色鏡片'],['金・映','柔金細框 / 淺茶鏡片'],['日・弧','飛行輪廓 / 漸層茶片'],['夜・序','經典黑框 / 深灰鏡片'],['霧・紫','幾何細框 / 紫色漸層'],['暮・光','大框輪廓 / 煙粉漸層']];
const hero=document.querySelector('#hero-image'),viewer=document.querySelector('#viewer');let current=-1,rx=0,ry=0,zoomed=false;
const products=document.querySelector('#products');frames.forEach((f,i)=>{const b=document.createElement('button');b.className='product reveal';b.setAttribute('aria-label','展示'+f[0]);b.innerHTML=`<div class="photo"><img src="assets/frame-${i+1}.jpeg" alt="${f[1]}" loading="lazy"></div><div class="product-title"><span>${f[0]}</span><small>0${i+1}</small></div><p>${f[1]}</p>`;b.onclick=()=>{select(i);document.querySelector('#home').scrollIntoView({behavior:'smooth'})};products.appendChild(b)});
const gallery=document.querySelector('#collection-gallery');frames.forEach((f,i)=>{const item=document.createElement('figure');item.className='collection-showcase reveal';item.innerHTML=`<div class="showcase-photo"><img src="assets/frame-${i+1}.jpeg" alt="${f[0]}，${f[1]}" loading="lazy"></div><figcaption><span class="showcase-number">0${i+1} / 06</span><h3>${f[0]}</h3><p>${f[1]}</p></figcaption>`;gallery.appendChild(item)});
const model=window.createEyewearViewer(viewer);let photoMode=!model;viewer.classList.toggle('has-3d',!!model);
function reset(){zoomed=false;document.querySelector('#zoom').setAttribute('aria-pressed','false');document.querySelector('#zoom').textContent='＋';model?.reset()}
function select(i){current=i;hero.src=`assets/frame-${i+1}.jpeg`;hero.alt=frames[i][1];document.querySelector('#product-name').textContent=frames[i][0];document.querySelector('#product-type').textContent=frames[i][1];document.querySelector('#product-number').textContent=`0${i+1} / 06`;document.querySelectorAll('.product').forEach((b,j)=>{b.classList.toggle('selected',j===i);b.setAttribute('aria-pressed',String(j===i))});model?.select(i);reset()}
const requestedFrame=new URLSearchParams(location.search).get('frame');select(/^[1-6]$/.test(requestedFrame)?Number(requestedFrame)-1:Math.floor(Math.random()*6));document.querySelector('#random').onclick=()=>select((current+1+Math.floor(Math.random()*5))%6);document.querySelector('#reset').onclick=reset;document.querySelector('#zoom').onclick=e=>{zoomed=!zoomed;e.currentTarget.setAttribute('aria-pressed',String(zoomed));e.currentTarget.textContent=zoomed?'−':'＋';model?.zoom(zoomed)};
const toggle=document.querySelector('#photo-toggle');toggle.onclick=()=>{photoMode=!photoMode;viewer.classList.toggle('has-3d',!photoMode);model?.show(!photoMode);toggle.textContent=photoMode?'返回 3D':'實拍照片';toggle.setAttribute('aria-pressed',String(photoMode));document.querySelector('#viewer-help').textContent=photoMode?'產品實拍照片':'單指旋轉 360° · 雙指縮放';document.querySelector('#zoom').disabled=photoMode;document.querySelector('#reset').disabled=photoMode};if(!model){toggle.hidden=true;document.querySelector('#viewer-help').textContent='此裝置無法顯示 3D · 目前顯示實拍照片';document.querySelector('#zoom').disabled=true;document.querySelector('#reset').disabled=true}
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');function close(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','開啟導覽選單');nav.classList.remove('open')}menu.onclick=()=>{let opened=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(opened));menu.setAttribute('aria-label',opened?'關閉導覽選單':'開啟導覽選單');nav.classList.toggle('open',opened)};nav.querySelectorAll('a').forEach(a=>a.onclick=close);document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();menu.focus()}});matchMedia('(min-width:801px)').addEventListener('change',close);if('IntersectionObserver'in window){const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e))}else document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));document.querySelector('#year').textContent=new Date().getFullYear();
